### ISSUE TITLE
geoutils version in outdated in conda feedstock

### ISSUE THREAD

**Issue by adehecq** [conda-forge/xdem-feedstock#16]
See at [this line](https://github.com/conda-forge/xdem-feedstock/blob/b9dd56fb2674c92693b3f0e5fe8700ffb5c0516e/recipe/meta.yaml#L42), the version indicated for the latest version of geoutils is 0.0.15, while we are now at version 0.1.5 and [xdem's environment](https://github.com/GlacioHack/xdem/blob/main/environment.yml) requires >0.1.5.

Therefore, if installing via conda-forge:
`mamba install -c conda-forge geoutils` -> yields version 0.1.5
`mamba install -c conda-forge xdem` -> forces a downgrade to 0.0.15

**Comment by rhugonnet** [comment]
This is all as expected! :smile: 
Latest xdem release `0.0.18` only works with geoutils `0.0.15` exactly. Only the main branch of xdem currently works with latest geoutils, in preparation for the next release!

**Comment by rhugonnet** [comment]
So the conda feedstock package dependency versions should match the ones of the latest published release (tar file in the "Releases" of the repo).

**Comment by adehecq** [comment]
Ok I'm convinced now!
